### ISSUE TITLE
Please add a new fn to MacAddress

### ISSUE THREAD

**Issue by espindola** [rep-nop/mac_address#4]
I am writing a program that handles mac addresses. I wanted to use the MacAddress struct, but there is no way to construct one from outside this library.
Adding a new fn similar to the one in std::net::Ipv4Addr would solve the problem.

**Comment by rep-nop** [comment]
Sure thing! I'll get to work on it and release a new version soon. :)

**Comment by rep-nop** [comment]
Fixed with the 0.7.0 release. Enjoy :)

**Comment by rep-nop** [comment]
Oh, and `PartialEq` was derived if you're doing direct comparisons.
